version: "3.9"

services:
  db:
    container_name: db_container
    image: postgres:14-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data.txt
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    networks:
      - db

  platform_blog:
    depends_on:
      - db
    networks:
      - db

  nginx:
    depends_on:
      - platform_blog
    networks:
      - db

volumes:
  pgdata:

networks:
  db:
